### ISSUE TITLE
Extent Reports - Junit structure

### ISSUE THREAD

**Issue by petuk** [anshooarora/extentreports#171]
Dear Anshoo,

First of all thanks for the great tool, it is really nice and useful for our Selenium test and it can be handle for the beginner java tester like me. :)

I have a question regarding the log. As I saw there is a possibility to add child test with appenChild, but that it worked for me only one test class. What I would like:
-package name1
----class name1
-------method name1
-------method name2
-------method nameN
----class name2
----class nameN
-------method name1
-------method name2
-------method nameN

-package name2
----class name1
.....
-package nameN
....

Is it possible somehow?
Thanks for your answer in advance,
Peter

**Comment by anshooarora** [comment]
At present, you can do the following:

```java
ExtentTest packageTest = extent.startTest("com.relevantcodes.extent");

ExtentTest method1 = extent.startTest("Extent.Method1");
method1.log(LogStatus.INFO, "Method1");

ExtentTest method2 = extent.startTest("Extent.Method2");
method2.log(LogStatus.INFO, "Method2");

packageTest
    .appendChild(method1)
    .appendChild(method2);

extent.endTest(packageTest);
extent.flush();
```

To create a structure as you have mentioned, it would involve a lot of clicking, which is why the layout was created in a way to directly access the test instead of clicking multiple levels.

It is very much possible though, by simply changing the template.  <a href='https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/view/Extent.ftl#L308'>Here</a> is the code.
