### ISSUE TITLE
If Test Step name is missing from very first log event

### ISSUE THREAD

**Issue by virenv** [anshooarora/extentreports#27]
These statements in TestBuilder   
   stepSrc = StepHtml.getSrc(2);      
 if (node.log.get(0).stepName != "") {
                stepSrc = StepHtml.getSrc(0);
            }
            
will make sure that the tests never have a TestStep name if the very first test log has no test name specified. Is this by design?

**Comment by anshooarora** [comment]
Hey Viren

Yes, this was by design and to prevent malformed tables.  After moving to version 2, I decided to keep this condition so only 1 sort of log is permitted for each test - so that if some steps have Steps and others don't, it shouldn't cause readability to suffer due to empty cells.

From:  http://extentreports.relevantcodes.com/2x/docs.html#create-step-logs

> There are 2 ways logs can be created: one that creates 3 columns and other that creates 4. Always use only 1 type of log for the test otherwise the table will become malformed.

**Comment by virenv** [comment]
Thanks for the clarification. Closing this.
