### ISSUE TITLE
Avoid need for loading unsafe scripts to view properly formatted report

### ISSUE THREAD

**Issue by testphreak** [anshooarora/extentreports#318]
Hi Anshoo, it's not a big deal to me, but for unfamiliar users of automation reports, they are greeted with a garbled page. So when I share my reports I am often told the page did not load properly. Only when they "load unsafe scripts" for example by clicking on the shield icon in the address bar in chrome, they can view the correctly formatted report.

Is this something you're aware of and may have a solution or future fix for?

**Comment by anshooarora** [comment]
If the report is served through a server you won't see this.  Also, your users must be opening via IE, which will throw this message because the HTML file is opened locally and resources are being loaded from http.

If hosting a web server is not an option then ibwoild recommend opening in Chrome or Firefox.

**Comment by testphreak** [comment]
Everybody I've shared the report with so far have only used Chrome first and Firefox second. We do host the results in a Bamboo server. I don't see it either. I'll close this as I'm unable to find a consistent way to reproduce.
