### ISSUE TITLE
Integration of extentreports in Cloud CI ?

### ISSUE THREAD

**Issue by afaucogney** [anshooarora/extentreports#328]
Just a quick, but maybe not so simple question:

I use a CI on Cloud to build and test my app. How can I use extentreports, and especially getting back the report ?

**Comment by dotautomation** [comment]
We're using the Jenkins CI to publish the HTML report generated by ExtentReports. It's working for the most part, except a nagging issue #332

**Comment by anshooarora** [comment]
I am really not sure about this.  With Jenkins though, a lot of people are hosting reports using the HTML publisher plugin.  

For #332, solution has already been posted in the same thread.

**Comment by drormik** [comment]
This issue is occurring when opening the file output html locally

I believe the issue is cause by using the 3  CDNs:

<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.min.css' type='text/css'>
<link href='https://cdn.rawgit.com/noelboss/featherlight/1.3.4/release/featherlight.min.css' type='text/css' rel='stylesheet' />
<link href='http://cdn.rawgit.com/anshooarora/extentreports/005d99e2f2716f6d749c77c65b57ca3c632c35a8/cdn/extent.css' type='text/css' rel='stylesheet' />

 is there a way to link the generated HTML to local CSS fiels instead of the remote CDNs  ?
since most test machines would not be connected to the internet  ..

**Comment by anshooarora** [comment]
There is an option to generate an offline report with NetworkMode.OFFLINE in the instance.
