### ISSUE TITLE
ExtentX

### ISSUE THREAD

**Issue by subratkumarmandal** [anshooarora/extentreports#345]
@anshooarora  can I see documentation of ExtentX I need to host the merged files.

**Comment by anshooarora** [comment]
Documentation will be available soon, and its not going to require you to merge files manually.  ExtentX is a NodeJS server and will only be used as a dashboard, similar to what ExtentMerge was doing but without any manual merging.  You will still using normal reporting with ExtentReports – which will be responsible for updating the database.  So in your run session, if you:
 
1.       Start an Extent instance using `new ExtentReports(“fileName”)`
2.       Add Tests, `flush()` out the report
3.       End test session
 
Steps 1-3 will become a report in ExtentReports HTML file and the same will also be available on the server.  So basically, ExtentReports is going to remain the primary reporting so you do not have to change anything in your tests, it will take care of communicating with the server/database too.  You will only have to add 1 line of code in your initialization, which is:
 
```java
ExtentReports extent = new ExtentReports(“filename”);
extent.x();  // add this to initialize communication with the backend
```
 
If in your current framework, you are already using ExtentReports, you will not have to change anything other than adding line#2 above.

**Comment by subratkumarmandal** [comment]
Yup we currently use  Extent reports in our framework to show reports.
I guess you will be releasing a new version to see extent.x(); 
I need to see what extent.x() does as we run it on jenkins any additional tools we need to download to have the backend .
Backend should be set up by us or how it will be ?

**Comment by anshooarora** [comment]
Yes, it will be available in next version.

Additional tools, yes..  NodeJs and MongoDB installation on local host or a dedicated machine acting as the server.  That's it.

You will see the alpha release very soon.

**Comment by testphreak** [comment]
Hi Anshoo, don't mean to jump the gun :smiley: but since most use cases would involve a dedicated server collecting results from CI runs, I am guessing you do allow specifying the URL to the dedicated server, yes?

Something like -
extent.x("http://10.2.815.90:8080/extentx") or through a configuration file.

Also, would be good if ExtentX supported the notion of a single Bamboo/Jenkins run consisting of multiple sub-runs/stages which are then merged, since we use TestNG's feature to re-run the failed tests from the previous stage of a run. That was a downside I saw with the other result aggregation tool I used previously called Cuanto, where it was hard to make meaningful conclusions because the first stage of a run would have say 30 failures, second stage of the same run 4 and third stage 0 for example. The next run (say run #2) would have 12 failures in the first stage, second stage 2 etc. So at a top level if ExtentX could report results from the overall run in the dashboard, and not individual stages at the top level that would be great. In the overall context of 3 stages in a run if 1 test failed, and there were 100 tests in total, the dashboard would report 1 failure for that run, instead of having 3 runs each with it's own failure count.

Not sure if all of this makes sense, so I'll be happy to explain in more detail in a separate thread if you'd prefer that.

**Comment by anshooarora** [comment]
Yes, you will be able to connect using one of the following:

```
x()
x(ServerAddress addr)
x(String host)
x(String host, int port)
x(MongoClientURI uri)
x(List<ServerAddress> seeds)
``

The scenario where re-runs being merged, I will have to research this because each time a new Extent instance is created, a new report json is created in Mongo.  The report ties all the tests/nodes/logs together in child collections. 

If stages #2 and #3 are executed in the same session, then the ability to overwrite test can be provided.  If different sessions (new instance of Extent created each time), not sure how it will be implemented.

**Comment by testphreak** [comment]
Yes, each stage in the run will be a new instance of Extent since it essentially is a new mvn integration-tests run. It's not an easy one to solve I agree. Maybe we can track runs by allowing the user to supply a variable, say for example, "numberOfStages". So in my case if it's 3, we could generate an id internally in ExtentX (ex: 1-<random Long>, where 1 is the run number and random int is the stage number) which could be used to track the different stages. Then merge the results of all stages that start with 1, once you the numberOfStages value is reached (in this case 3). There are occasions when Bamboo/Jenkins may hang and not run all stages, in that case I guess you might need to allow user to provide a timeout value.

Hope that makes sense. I could be over simplifying and maybe you have better ideas. Don't know a lot about MongoDB, but I guess your concern is since MongoDB not a traditional relational database, merging may not be straightforward?

Would have been cool if we could white board this together! But let me know if you would like me to explain the problem statement better. This feature would be super useful to a lot of folks who use the testng-failed.xml file which contain the test failures from a run to re-run them again in the next stage of the same run to eliminate false failures. Use cases where this is useful is when there are temporary environment issues or concurrency/multi-threading issues.

**Comment by anshooarora** [comment]
We can also chat on gitter:  https://gitter.im/anshooarora/extentreports

How about providing the ability to select the reports in the dashboard and click "merge" to automatically create a single report and show the last updated run status?

**Comment by testphreak** [comment]
That's an option too, but if I understood it correctly that would mean someone having to manually go to the dashboard page after every run and checking the ones that apply and merging them. The other issue that could happen there is someone choosing the stages incorrectly on the page and merging them.

I am just trying to make it as automated as possible. Also, since a lot of team are moving towards daily deployments, anything manual could end up with mistakes and taking time.

**Comment by ansonliao** [comment]
@anshooarora
Hope see ExtentX soon.
BTW, could you add feature that get report URL?
For example, once uploaded extentreport to ExtentX server, maybe each test method will have a separated extentreport (testng), after uploaded extentreport, have a method to get the report URL of ExtentX.

**Comment by anshooarora** [comment]
I don't think this will be possible - to get the corresponding report URL as your nodejs server can be on a different box than mongodb.  I can provide the report I'd which you can use to query and see the report in x.

The first release will be available in a few days, hopefully this or next week.  Still need to work on docs.
