### ISSUE TITLE
How can we stop/restrict propagating the results of child nodes from bottom to the top parent

### ISSUE THREAD

**Issue by meenakshi127616** [anshooarora/extentreports#360]
![issue_extent report](https://cloud.githubusercontent.com/assets/17696918/13600066/7a9c2e10-e54c-11e5-9455-753623a3afb0.PNG)
![Uploading image.png…]()

In summary:
We want to run our tests on 3 browsers and every test will have some iterations underneath test cases just as given below 
Browser01 (Parent)
    - Test Case01 (Child L1)
             - Iteration 1 (Child L2)
             - Iteration 2 (Child L2)
Now if Iteration 1 gets "Pass" and Iteration 2 gets "Fail" than TestCase 01 is also displayed as "Fail" and Browser01 is Also "Fail" as result of child nodes are propagating upwards This has 2 problems
1. It is giving an impression that broswer01 is failed even if a single test iteration among hundreds of test cases gets failed.
2. A wrong test summary is presented, for instance for the above example quoted a single iteration failure for a test case. results in 1 Pass, 3 Fail (1 for Browser, 1 for Testcase, 1 for Iteration). Instead of showing 1 Pass and 1 Fail.

**Comment by email2vimalraj** [comment]
@meenakshi127616: 

For the point # 1: This is the expected behavior. In an ideal situation, everyone wanted to fail the parent or grand parent, even if one of the child fails. Your case is very specific.
# 2: Use 2.40.2 which has some fixes related to this. You will have to anyway filter to show only the child test counts. Click on three vertical dots present in right top corner in the Tests View panel and select Child Tests only.

**Comment by meenakshi127616** [comment]
1. I need to change this expected behavior as Test step counter is incorrect as told before. It is giving an impression that parent is failed even if a single test iteration among hundreds of test cases which are getting failed.

2. Filter count doesn't show properly even when i select 
a.parent tests without child tests or
b. option child tests 
since my hierarchy is 3 level.
both options show same result because of expected behavior of parent failing even if one of the child fails.
3rd option c.parent tests only just shows topmost parent count which is correct but i need count for 
TestCases for following hierarchy
Browser01 (Parent)
- Test Case01 (Child L1)
- Iteration 1 (Child L2)
- Iteration 2 (Child L2)

**Comment by testphreak** [comment]
All this you described should be expected behavior from any reporting framework where a parent fails when one or more of it's children fail.

I suggest refactoring your framework to not follow a parent-child implementation and instead have each test, report it's results like most of us do. Also update your CI plan to include say 3 stages where each stage in the run executes against a browser (ex: 1st stage FF, 2nd stage Chrome etc). At the end of your run you would collate results from the 3 stages and derive conclusions from each report that gets generated from each stage. Or you can configure your CI plan to do 3 runs, one after the other, against each browser.

**Comment by meenakshi127616** [comment]
how to include 3 stages where each stage in the run executes against a browser,
please provide sample code.
Is it like making 3 categories for browsers?what about 3 level hierarchy,still my Iterations remain childs of Testcases?or i should try that also in some other way without parent-child.

Browser01 (Parent)

Test Case01 (Child L1)

             - Iteration 1 (Child L2)
             - Iteration 2 (Child L2)

**Comment by meenakshi127616** [comment]
Could you please elaborate what do you mean by refactoring your framework to not follow a parent-child implementation and instead have each test, report it's results,because i am already following the stage wise execution for every browser. My tests are running in 3 browsers sequentially i.e. first they are running of Firefox than IE and at last chrome. But i wanted to collate result in a single report rather than generating 3 reports (1 for each browser).How to  update  CI plan to include say 3 stages where each stage in the run executes against a browser (ex: 1st stage FF, 2nd stage Chrome etc). how to configure CI plan to do 3 runs, one after the other, against each browser.

**Comment by meenakshi127616** [comment]
Any help would be appreciated as i was exploring different features of this report but could not get much help from this page.
Please provide sample code or any example for the same.
or any basic idea how i can solve this issue.

**Comment by anshooarora** [comment]
As Vimal mentioned above, this is a very specific case and not currently possible. All child test categories will automatically be displayed at the parent level.
