### ISSUE TITLE
No Report generated in Offline Mode and no Temporary html files if program execution stops due to some reasons unlike version1?

### ISSUE THREAD

**Issue by meenakshi127616** [anshooarora/extentreports#366]
###1.If i execute my program without internet connection,report generated in offline mode is absurd.

2. No temporary html files if program execution stops due some reasons in between,report only gets generated after all @Test completion unlike version1 wherin several temporary reports were generated in between also.

How can i handle these scenerios of Internet connection and program forceful interruption/Stoppage?

**Comment by testphreak** [comment]
Generally your issues are verbose. Break down the problem into points and show us what you've tried so far with code. Adding screenshots also helps support your issue. Use Markdown to help you correctly format your issue.

Also remember, you are likely to receive helpful pointers from community members when the feedback in constructive.

Having said that, using flush() after every test method and close() after the entire suite has run, should ensure that your results get printed to your already created report. So even if the run/session halts, you should still be able to recover a report with partial results. Never used offline mode before, so can't help you there. I tend to wonder what the use case for offline report may be, since your machine and the build/CI hosts are almost always online.

**Comment by meenakshi127616** [comment]
I mean to say that ,if i make a new report everytime with date_timestamp,
no Temporary html files are generated .

for example if i have 3 Tests as TestNG tests and my internet connectivity goes then i do not get a report until the time where my net connection lost,

i want a report till that time before my connection lost,now i am writing report.flush() at end of all tests,
so my program can stop at any time hence i cannot write extent.flush() at every place since the place of stoppage is dynamic.

so how do i make sure that report is generated till the point of stoppage.

**Comment by meenakshi127616** [comment]
no report in offline mode means if i run my code using extent report jar,
 my report is not the actual report template because of the reason
 that it is picking javascript template of report from internet ,
which means this issue can be resolved if i copy .js file to my local drive and give its path to make report  instead of using online javascript template.

**Comment by anshooarora** [comment]
All artifacts are saved locally when instantiated in OFFLINE mode.  Why would the artifacts be picked from the internet? If you analyze the source, this is what the script tag displays:

```
<script type='text/javascript' src='./extentreports/js/scripts.js'></script>
```

You can flush out the report after each test, the report will be updated once a test is complete.
