### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#372]
Hi,

Can create a API to navigate within a directory that contains reports ExtentReports and see from there it these besides being able to merge with ExtentX?

Thanks you.

**Comment by anshooarora** [comment]
Actually, there will be no longer any manual steps to merge reports.  What will happen is:

- Your test runs and ExtentReports is used to build your report
- ExtentReports stores entire test information in the database (MongoDB)
- ExtentX is a Node server, will query MongoDB and show each report 

I am currently working on a way to link the static HTML files to the server so you can directly access them instead of ExtentX creating them again as you current see under the reports view:  http://extentx.herokuapp.com/reportDetails?id=56df02f94d1c561f74a76c68

**Comment by MaxiTalenti** [comment]
Perfect!,


I also like going to see ideas come as reports that are running tests or appear in status "in process"
You could try ExtentX ?
Thank you!

**Comment by anshooarora** [comment]
Not sure how to implement 'in progress' status.. since, users always use `flush()` to write to the report.  It would be quite easy if users always use `close()` method but this is not always the case.  Any idea how this can be implemented?

**Comment by MaxiTalenti** [comment]
You understand, as the report is written using Flush () is practically impossible.
My idea was that the report is visible from the first moment, the first step, then this way the report will only be updated as is happening the test, then from ExtentX you could be watching the progress of a test running as that time passes (this would serve much for test cases to delay too long).
It understands what I mean?

**Comment by anshooarora** [comment]
A similar question was asked recently,  my response [here](https://github.com/anshooarora/extentreports/issues/459#issuecomment-217507543): 

> I checked this, and the last reported status will be displayed by default instead of "in-progress" or "unknown". If no logs have been added to the test, then the status will be displayed as "unknown". This feature is likely to not change anytime soon as the final status of the test will only be displayed once its complete and will require comprehensive testing if a change is made here.
