### ISSUE TITLE
Error in test result

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#397]
![failtag](https://cloud.githubusercontent.com/assets/7159779/14079075/4f28b91c-f4d1-11e5-8f4d-0bc9e4ac490f.jpg)

**Comment by anshooarora** [comment]
Do you mean the formatting?  Please provide more details about the issue

**Comment by MaxiTalenti** [comment]
This occurred when creating several tests in different executions on the same file.

**Comment by jawlitkp** [comment]
Please note same formatting issue is there for "unknown" tag

**Comment by anshooarora** [comment]
Fixed, but for info, this is due to the display size.  You can expand the container and it will automatically be correctly placed.  I have set the formatting to be displayed correctly for smaller display sizes upto 1124px.  If you have a display larger than that, you should have no issues.  For smaller displays, simply resize the container.
