### ISSUE TITLE
Category and Defect View does not display in ExtentX  Report

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#420]
Hi Anshoo,

I have used the Extent X jar file with mongodb , and report is generated successfully . But There are few things missing in the report compare to ExtentReport .

1.Category view does not display when category is assigned 
2.Defect view does not display when test are failed 

I think it would be nice to have the same view as it is in Extent report or something new with Category and Defect view .

I have attached the screen shot below
![extentx](https://cloud.githubusercontent.com/assets/10355092/14491239/531744aa-0195-11e6-9206-6de92a9b2ebc.png)

**Comment by anshooarora** [comment]
You can log an enhancement on the extentx page and if there is enough support, we can consider developing these feature.  But remember, since ExtentX is an analysis tool, it is not supposed to replace ExtentReports.  We can make it possible to link report files with the server so you can access and look at the category/bug view from there..
