### ISSUE TITLE
New Feature: Test case number and Test step number

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#442]
Hi Anshoo,

Would you be able to do something like below screenshot.

[2016-04-21_8-17-25.pdf](https://github.com/anshooarora/extentreports/files/229867/2016-04-21_8-17-25.pdf)

**Comment by anshooarora** [comment]
This functionality has been previously requested but it takes too much real-estate which is why it wasn't included.  To do this directly in the template, you can:

- add indexes right before [this line](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/resources/com/relevantcodes/extentreports/view/Extent.ftl#L294) and [this line](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/resources/com/relevantcodes/extentreports/view/Extent.ftl#L380)

In FreeMarker, you can get the counter using [this](http://freemarker.org/docs/ref_builtins_loop_var.html#ref_builtin_counter) so you will have the counter for tests as well as logs:

```
// tests
<span class='label info'>${test?counter}</span>

// logs
<span class='label info'>${log?counter}</span>
```

If you don't want to do this directly in the template, it will be a little messy, but for tests, I would suggest doing something like this in your `@AfterMethod`:

```
int ctr = 0;

@AfterMethod
public void afterMethod() {
    ctr++;
    String name = extentTest.getTest().getName();
    String label = "<span class='label info'>" + ctr + "</span>&nbsp;";
    
    extentTest.getTest().setName(label + name);
}
```
