### ISSUE TITLE
Question: in-progress status for currently running test cases 

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#459]
Hi Anshoo,

Is there any way ,startTest() methods can log test case status as in progress until endTest() writes actual status , when i am calling report.flush(), it creates html report and shows up test cases status as pass for currently running test cases and as soon as endTest() method gets called it writes actual status.

So what i want to see is when i call report.flush().it should show up test case status as in progress and endTest() method should write actual status.  so that way you know what test cases are in progress during execution is running

Thanks

**Comment by karthikbhatnagar** [comment]
This would be a good feature. Can this be applied to extentx also?

**Comment by anshooarora** [comment]
I will check and let you know, although the default status when the test starts is UNKNOWN so it shouldn't be displayed as Pass.

**Comment by anshooarora** [comment]
I checked this, and the last reported status will be displayed by default instead of "in-progress" or "unknown".  If no logs have been added to the test, then the status will be displayed as "unknown".  This feature is likely to not change anytime soon as the final status of the test will only be displayed once its complete and will require comprehensive testing if a change is made here.  Feel free to open an ER for this though, and @karthikbhatnagar - for ExtentX.
