### ISSUE TITLE
Video required for ExtentX

### ISSUE THREAD

**Issue by ranashahan** [anshooarora/extentreports#482]
Hi,

Can you please provide me link of any video tutorial of Extendx report which connected with mongodb. I tried to find it on youtube and google it but no luck :(.

If any video tutorial have following items that will be good enough for me and other audience hopefully  

1. Install node js on VM machine.
2. Install mongodb on vm machine.
3. Connect ExtendX with mongodb (VM server URL) through java code.
4. Generate multiple reports and merge with Extendx.

Sorry for being dump, but i am not coder and i can't implement correctly as per your following guidance.  I tried multiple times but i failed .
http://extentreports.relevantcodes.com/extentx/
http://extentreports.relevantcodes.com/java/#connect-to-extentx 

Thanks 
Rana.

**Comment by ranashahan** [comment]
Hi Anshoo,

Any chance to give a little help??

**Comment by anshooarora** [comment]
Hi, sorry, I haven't had a chance to work on this due to very little bandwidth to focus on open-source these days.  From the ExtentX installation page:

#### MongoDB & NodeJS on same host

* Download and install NodeJS
* Download and install MongoDB
  * Run Mongo daemon
    * Open Console
    * Navigate to MongoDB folder
    * Run mongod
* Download ExtentX, unzip, navigate to its folder and run:
*  npm install
*  sails lift

Seems you have done the installation.  Now, you can open a console (cmd), and go to the directory where MongoDB is installed (while in console):

```
cd mongodb-installation-folder\bin
mongod
```

After that, unzip ExtentX folder, and go to the root of the folder where you will see the following files:  https://github.com/anshooarora/extentx

Here, type: 

```
npm install
sails lift
```

Now, run your tests as you would normally by simply adding this line of code right after creating ExtentReports instance:

```
ExtentReports extent = new ExtentReports("..."); // create instance 
extent.x(); // connect to mongodb
```
