### ISSUE TITLE
To get step wise report

### ISSUE THREAD

**Issue by revathyvarma** [anshooarora/extentreports#485]
Hi,

I have use the ExtentReporterNG listener and working in the same way as given in the blog.I am getting a html report with test case pass/fail details.
Could you please tell me how can i get details of test steps.I am urrently using a maven based testng selenium frameowrk.

**Comment by anshooarora** [comment]
If you are trying to tie listener with normal logging, I have seen some people achieve this, but its a pretty complicated task because..  

1. Normal logging occurs while your test is in session
2. TestNG listener executes when all the tests have finished

So you would have to tie the results of 1 with 2.  You can search other posts that deal with the same issue as I am not sure how others have implemented this - I generally recommend against this.  Its better to use a single approach to keep the reporting simple.
