### ISSUE TITLE
addScreenShot to ExtentTest is not read while creating the report

### ISSUE THREAD

**Issue by toolsqa** [anshooarora/extentreports#6]
Problem: In v2 we have moved screenshot to ExtentTest class. I am using addScreenshot to add a particular screenshot. There are two issues that I am facing

- addScreenshot adds the image html in the ArrayList of ScreenCapture, however it does not add this html in the final html generated. In TestBuilder I dont see any step replacement for ScreenShots or ScreenCasts. As a result if we have simple dont ExtentTest.addScreenshot(), it will not appear in the report.
- In v1 we had attachScreenShot which used to take the path to the screen and also used to take a message. In V2 its only addScreenshot which doesnt take a message.

I am not sure if these are design or a bug. In v2 addScreenshot returns you the HTML of screenshot. This way we can write following code to add a screenshot
''''Java
 String ScreenShotHtml = reporter.addScreenCapture(takeScreenShot());
    reporter.log(LogStatus.INFO, ScreenShotHtml);
''''

**Comment by anshooarora** [comment]
Do you find the functionality of v1 better?  I can code it same as before if that is more meaningful.

Also,  you have accurately identified the functionality.  This is actually by design.  addScreenCapture will add the path to the test and the path can be supplied to the any log event as shown here:  

http://extentreports.relevantcodes.com/2x/docs.html#insert-screenshots

This way the snapshot can be tied to the step/details in the same row in the table.

**Comment by toolsqa** [comment]
Well, looking at the document it seems fine. So basically the correct usage should be that if a test step fails and you want to add a screenshot, you will have to add a log with LogStatus as fail and if its a waring a LogStatus as warning and attach the screenshot.

Just by thinking of it aloud I think this behavior is good. Lets not code to change the behaviour, let me use it more and I will add more feedback.

Thanks for this wonderful reporting system. Parallel reports work absolutely fine for me.

**Comment by toolsqa** [comment]
I will close this issue based on the above comment.

Thanks
