### ISSUE TITLE
In extent report log, multi-byte chars are shown as question marks

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#65]
Env:
Extent report 2.04.jar

Hi, while testing the data contains multibyte chars. when added the test step information to the extent report i see multibyte chars as question marks.

Thanks
Madhusudhan G
![Uploading multibyte_chars_are_shown_as_questionmarks.png…]()

**Comment by anshooarora** [comment]
The image/file didn't come through..

**Comment by gsaimadhu** [comment]
![multibyte_chars_shown_as_questionmarks](https://cloud.githubusercontent.com/assets/8359360/9517761/d0d51e10-4ccf-11e5-8270-adc4e7f8fb3b.jpg)

uploaded the snapshot, Please let me know if it is proper.

**Comment by anshooarora** [comment]
I have tested these characters on the report and they all render correctly because starting 2.031, the UTF-8 charset is being used:

```
<meta http-equiv='content-type' content='text/html; charset=utf-8' /> 
```

The issue may be with your IDE, see this for example:  http://stackoverflow.com/questions/15522688/multibyte-character.  You may have to set the correct encoding in your IDE and try again.

**Comment by gsaimadhu** [comment]
Anshoo,

Thanks, now the multibyte chars are showing fine, after changing the
encoding in run configuration.

Madhusudan G

**Comment by ankit9289** [comment]
@anshooarora - I am using IntelliJ still same problem...and Encoding is set to UTF-8

**Comment by edumaxsantos** [comment]
@anshooarora same problem here. The html file is being generated with ANSI encoding. I believe that may be the issue
